on:
  pull_request:
    types: [opened, reopened]
    branches: [main]
  workflow_dispatch:
jobs:
  poc-lambda-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - run: |
          cd poc-lambda
          python3 -m unittest discover ./tests -p 'test_*.py'
