name: Terraform apply
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  terraform-dev-deployment:
    uses: nationalarchives/tre-blueprint-test-repository/.github/workflows/test-terraform-action.yml@feature/DTE-432/initial-terraform-config
    with:
      environment: dev
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_VARS_KEY: ${{ secrets.AWS_PARAM_STORE_TF_VARS_KEY }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  terraform-test-deployment:
    needs:
      - terraform-dev-deployment
    uses: nationalarchives/tre-blueprint-test-repository/.github/workflows/test-terraform-action.yml@feature/DTE-432/initial-terraform-config
    with:
      environment: test
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_VARS_KEY: ${{ secrets.AWS_PARAM_STORE_TF_VARS_KEY }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  deploy-to-int-checkpoint:
    needs: 
      - terraform-test-deployment
    runs-on: ubuntu-latest
    environment: poc-manual-step
    steps:
      - name: Manual Approve Info
        run: |
          echo ${{ github.triggering_actor }}
          echo ${{ github.actor }}
  terraform-int-deployment:
    needs: 
      - deploy-to-int-checkpoint
    runs-on: ubuntu-latest
    steps:
      - name: To do
        run: |
          echo ${{ github.triggering_actor }}
          echo ${{ github.actor }}
  