name: test-action
on:
  push:
    branches:
      - feature/DTE-421/initial-test-action
jobs:
  example-job-1:
    env:
      example_env_var: 'Alpha, bravo, charlie'
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: |
          printf 'example_env_var=%s\n' "${example_env_var}"
  example-job-2:
    runs-on: ubuntu-latest
    needs: example-job-1
    environment: poc-manual-step
    steps:
      - name: Test poc-manual-step
        run: |
          printf 'Test poc-manual-step\n'
  example-job-3:
    runs-on: ubuntu-latest
    needs: [example-job-1, example-job-2]
    steps:
      - name: Test Job 3/1
        run: |
          printf 'Test 3/1\n'
