name: test-action
on:
  push:
    branches:
      - feature/DTE-432/initial-terraform-config
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: |
          printf 'Test 1\n'
      - name: Test 2
        run: |
          print('Test 2.1')
          print('Test 2.2')
        shell: python
      - name: Configure AWS credentials for test AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: eu-west-2
          role-session-name: InternalGitHubActionsRoleName
      - name: AWS Access Test
        run: |
          aws --version
          date > test-date.txt
          aws s3 cp test-date.txt s3://dev-te-testdata/tmp/test-date.txt
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Terraform Init
        run: |
          echo ${{ tf_backend }} | backend.conf
          pwd
          ls -la
          cd test-terraform
          terraform init -backend-config=backend.conf
          terraform workspace list
