name: Terraform platform deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment you want to deploy to from the dropdown list
        options:
          - platform
permissions:
  id-token: write
  contents: write
jobs:
  terraform-deployment:
    uses: nationalarchives/tre-blueprint-test-repository/.github/workflows/tre-platform-actions.yml@feature/DTE-432/initial-terraform-config
    with:
      environment: ${{ inputs.environment }}
      env_vars: tre-platform
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_VARS_KEY: ${{ secrets.AWS_PARAM_STORE_TF_VARS_KEY }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      TF_VAR_TERRAFORM_ASSUME_ROLES: ${{ secrets.TF_VAR_TERRAFORM_ASSUME_ROLES }}
